import { fontFamily } from './fonts'

const Icons = {
    telegram: require('./icons/telegram.png'),
    alert: require('./icons/alert.png'),
    announce: require('./icons/announce.png'),
    backArrow: require('./icons/back.png'),
    bellIcon: require('./icons/bellIcon.png'),
    chartIcon: require('./icons/chart.png'),
    tick: require('./icons/check.png'),
    clock: require('./icons/clock.png'),
    cross: require('./icons/close.png'),
    doneIcon: require('./icons/done.png'),
    downArrow: require('./icons/downarrow.png'),
    emailIcon: require('./icons/email.png'),
    closedEyeIcon: require('./icons/eye-off.png'),
    eyeIcon: require('./icons/eye.png'),
    failed: require('./icons/failed.png'),
    fixIcon: require('./icons/fix.png'),
    flaskIcon: require('./icons/flask.png'),
    homeIcon: require('./icons/homes.png'),
    keyIcon: require('./icons/key.png'),
    linkIcon: require('./icons/link.png'),
    lockIcon: require('./icons/lock.png'),
    redLock: require('./icons/lockIcon.png'),
    menuIcon: require('./icons/menu.png'),
    messageIcon: require('./icons/message.png'),
    settingsIcon: require('./icons/star.png'),
    passcodeIcon: require('./icons/passcode.png'),
    phoneIcon: require('./icons/phone.png'),
    userIcon: require('./icons/user.png'),
    userProfileIcon: require('./icons/userProfile.png'),
    secureIcon: require('./icons/secure.png'),
    calender: require('./icons/calender.png'),
    gallery: require('./icons/gallery.png'),
    avatar: require('./icons/Avatar.png'),
    camera: require('./icons/Camera.png'),
    arrow: require('./icons/arrow.png'),
    dropdown: require('./icons/dropdown.png'),
    search: require('./icons/search.png'),
    messIcon: require('./icons/chat.png'),
    moreIcon:require('./icons/more.png'),
    addIcon:require('./icons/add.png'),
    deleteIcon:require('./icons/delete.png'),
    pinIcon:require('./icons/pin.png'),
    plusIcon:require('./icons/icon.png'),
    binIcon:require('./icons/bin.png'),
    likeIcon:require('./icons/like.png'),
    dislikeIcon:require('./icons/dislike.png'),
    heartIcon:require('./icons/heart.png'),
    confettyIcon:require('./icons/confetty.png'),
    laughIcon:require('./icons/laugh.png'),
    replyIcon:require('./icons/reply.png'),
    report:require('./icons/report.png'),
    stars:require('./icons/stars.png'),
    copy:require('./icons/copy.png'),
    forwardIcon:require('./icons/corner-up-right.png'),
    deleteModalIcon:require('./icons/bindelete.png'),
   
};

const Images = {
    backDrop: require('./images/backdrop.png'),
    background: require('./images/background.png'),
    color: require('./images/Color.png'),
    landingImage: require('./images/Landing.png'),
    onboardingImage: require('./images/onboard.jpg'),
    popupImage: require('./images/popup.png'),
    tutorialImage: require('./images/tuto.jpg'),
    logoImage: require('./images/Whiteicon.png'),
    profilePic: require('./images/profilepic.png'),
    emptyIamge:require('./images/empty.png'),
    searchImage:require('./images/searchImage.png'),
    splash:require('./images/splash.png'),
}

export { Images, Icons, fontFamily }